NEXT_PUBLIC_SUPABASE_URL=https://nkaxhubwzgjtkjftemlx.supabase.co
NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rYXhodWJ3emdqdGtqZnRlbWx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NjM1MTQsImV4cCI6MjA4ODMzOTUxNH0.BoRcPW0zFzwuMvhzHqgHFMw5PB9VxuifZg2pR2I6j6c


import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

export const supabase = createClient(supabaseUrl, supabaseAnonKey)